name: dozergame
description: Snake but much better
version: 1.0.0
homepage: https://webtech.mylab.th-luebeck.de/ss2019/team-4a/
authors:
  - Jan Steffen Krohn <jan.steffen.krohn@stud.th-luebeck.de>
  - Tom Christopher Böttger <tom.boettger@stud.th-luebeck.de>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  pwa: '>=0.1.2'

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
