name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          wget https://storage.googleapis.com/dart-archive/channels/stable/release/2.1.0/linux_packages/dart_2.1.0-1_amd64.deb
          sudo apt install ./dart_2.1.0-1_amd64.deb
          export PATH="$PATH:/usr/lib/dart/bin"
          echo $PATH
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          echo $PATH
          pub global activate webdev
          echo $PATH
          pub get
          webdev build --output web:build
          dartdoc --output build/doc --exclude generator
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
